sonar.projectKey=discocs
sonar.sources=app,discocs_bot/bot,ui/src
sonar.tests=tests,discocs_bot/tests,ui/tests
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
